author: Miguel Nieto
author_url: https://github.com/m-lab
github_url: https://github.com/m-lab/ndt7-client-ios
output: docs
theme: fullwidth
readme: README.md
module: NDT7
xcodebuild_arguments: [-workspace, 'NDT7.xcworkspace', -scheme, 'NDT7 iOS']
